import os
import re
import subprocess
import sys
from pathlib import Path
from shutil import copyfile
from shutil import rmtree
from os import listdir

if sys.version_info[0] < 3:
    raise Exception("Python 3 or a more recent version is required.")

# Imports Gecko code for building in Servo.

header_files = [
    ("dom/media/AudioConverter.h", "AudioConverter.h"),
    ("dom/media/AudioDeviceInfo.h", "mozilla/dom/AudioDeviceInfo.h"),
    ("dom/media/AudioSampleFormat.h", "AudioSampleFormat.h"),
    ("dom/media/AudioStream.h", "AudioStream.h"),
    ("dom/media/CubebUtils.h", "CubebUtils.h"),
    ("dom/media/Intervals.h", "Intervals.h"),
    ("dom/media/MediaData.h", "MediaData.h"),
    ("dom/media/MediaEventSource.h", "MediaEventSource.h"),
    ("dom/media/MediaInfo.h", "MediaInfo.h"),
    ("dom/media/MediaResult.h", "MediaResult.h"),
    ("dom/media/platforms/PlatformDecoderModule.h", "PlatformDecoderModule.h"),
    ("dom/media/SharedBuffer.h", "SharedBuffer.h"),
    ("dom/media/StreamTracks.h", "StreamTracks.h"),
    ("dom/media/systemservices/OSXRunLoopSingleton.h", "OSXRunLoopSingleton.h"),
    ("dom/media/TimeUnits.h", "TimeUnits.h"),
    ("dom/media/TrackID.h", "TrackID.h"),
    ("dom/media/VideoLimits.h", "VideoLimits.h"),
    ("dom/media/VideoUtils.h", "VideoUtils.h"),
    ("gfx/2d/2D.h", "mozilla/gfx/2D.h"),
    ("gfx/2d/BaseCoord.h", "mozilla/gfx/BaseCoord.h"),
    ("gfx/2d/BaseMargin.h", "mozilla/gfx/BaseMargin.h"),
    ("gfx/2d/BasePoint.h", "mozilla/gfx/BasePoint.h"),
    ("gfx/2d/BasePoint3D.h", "mozilla/gfx/BasePoint3D.h"),
    ("gfx/2d/BasePoint4D.h", "mozilla/gfx/BasePoint4D.h"),
    ("gfx/2d/BaseRect.h", "mozilla/gfx/BaseRect.h"),
    ("gfx/2d/BaseSize.h", "mozilla/gfx/BaseSize.h"),
    ("gfx/2d/Coord.h", "mozilla/gfx/Coord.h"),
    ("gfx/2d/FontVariation.h", "mozilla/gfx/FontVariation.h"),
    ("gfx/2d/GenericRefCounted.h", "mozilla/GenericRefCounted.h"),
    ("gfx/2d/LoggingConstants.h", "mozilla/gfx/LoggingConstants.h"),
    ("gfx/2d/Matrix.h", "mozilla/gfx/Matrix.h"),
    ("gfx/2d/MatrixFwd.h", "mozilla/gfx/MatrixFwd.h"),
    ("gfx/2d/NumericTools.h", "mozilla/gfx/NumericTools.h"),
    ("gfx/2d/Point.h", "mozilla/gfx/Point.h"),
    ("gfx/2d/Quaternion.h", "mozilla/gfx/Quaternion.h"),
    ("gfx/2d/Rect.h", "mozilla/gfx/Rect.h"),
    ("gfx/2d/ScaleFactor.h", "mozilla/gfx/ScaleFactor.h"),
    ("gfx/2d/ScaleFactors2D.h", "mozilla/gfx/ScaleFactors2D.h"),
    ("gfx/2d/Tools.h", "mozilla/gfx/Tools.h"),
    ("gfx/2d/Triangle.h", "mozilla/gfx/Triangle.h"),
    ("gfx/2d/Types.h", "mozilla/gfx/Types.h"),
    ("gfx/2d/UserData.h", "mozilla/gfx/UserData.h"),
    ("gfx/layers/ImageTypes.h", "ImageTypes.h"),
    ("gfx/layers/ipc/KnowsCompositor.h", "mozilla/layers/KnowsCompositor.h"),
    ("gfx/layers/CompositorTypes.h", "mozilla/layers/CompositorTypes.h"),
    ("gfx/layers/LayersTypes.h", "mozilla/layers/LayersTypes.h"),
    ("gfx/cairo/libpixman/src/pixman.h", "pixman.h"),
    ("gfx/cairo/libpixman/src/pixman-version.h", "pixman-version.h"),
    ("gfx/cairo/cairo/src/pixman-rename.h", "cairo/pixman-rename.h"),
    ("gfx/src/ArrayView.h", "mozilla/ArrayView.h"),
    ("gfx/src/AppUnits.h", "mozilla/AppUnits.h"),
    ("gfx/src/nsMargin.h", "nsMargin.h"),
    ("gfx/src/nsPoint.h", "nsPoint.h"),
    ("gfx/src/nsRect.h", "nsRect.h"),
    ("gfx/src/nsRegion.h", "nsRegion.h"),
    ("gfx/src/nsCoord.h", "nsCoord.h"),
    ("gfx/src/nsRegionFwd.h", "nsRegionFwd.h"),
    ("gfx/src/nsSize.h", "nsSize.h"),
    ("gfx/thebes/gfxPoint.h", "gfxPoint.h"),
    ("gfx/thebes/gfxPrefs.h", "gfxPrefs.h"),
    ("gfx/thebes/gfxTypes.h", "gfxTypes.h"),
    ("gfx/ycbcr/YCbCrUtils.h", "YCbCrUtils.h"),
    ("intl/unicharutil/util/nsUnicharUtils.h", "nsUnicharUtils.h"),
    ("intl/strres/nsStringBundleService.h", "nsStringBundleService.h"),
    ("layout/style/ServoUtils.h", "mozilla/ServoUtils.h"),
    ("layout/base/Units.h", "Units.h"),
    ("media/libcubeb/include/cubeb-stdint.h", "mozilla/media/libcubeb/include/cubeb-stdint.h"),
    ("media/libcubeb/include/cubeb.h", "mozilla/media/libcubeb/include/cubeb.h"),
    ("media/libcubeb/include/cubeb_export.h", "mozilla/media/libcubeb/include/cubeb_export.h"),
    ("media/libcubeb/src/android/audiotrack_definitions.h", "mozilla/media/libcubeb/src/android/audiotrack_definitions.h"),
    ("media/libcubeb/src/android/sles_definitions.h", "mozilla/media/libcubeb/src/android/sles_definitions.h"),
    ("media/libcubeb/src/audiotrack_definitions.h", "mozilla/media/libcubeb/src/audiotrack_definitions.h"),
    ("media/libcubeb/src/cubeb-internal.h", "mozilla/media/libcubeb/src/cubeb-internal.h"),
    ("media/libcubeb/src/cubeb-sles.h", "mozilla/media/libcubeb/src/cubeb-sles.h"),
    ("media/libcubeb/src/cubeb-speex-resampler.h", "mozilla/media/libcubeb/src/cubeb-speex-resampler.h"),
    ("media/libcubeb/src/cubeb_array_queue.h", "mozilla/media/libcubeb/src/cubeb_array_queue.h"),
    ("media/libcubeb/src/cubeb_assert.h", "mozilla/media/libcubeb/src/cubeb_assert.h"),
    ("media/libcubeb/src/cubeb_log.h", "mozilla/media/libcubeb/src/cubeb_log.h"),
    ("media/libcubeb/src/cubeb_mixer.h", "mozilla/media/libcubeb/src/cubeb_mixer.h"),
    ("media/libcubeb/src/cubeb_osx_run_loop.h", "mozilla/media/libcubeb/src/cubeb_osx_run_loop.h"),
    ("media/libcubeb/src/cubeb_panner.h", "mozilla/media/libcubeb/src/cubeb_panner.h"),
    ("media/libcubeb/src/cubeb_resampler.h", "mozilla/media/libcubeb/src/cubeb_resampler.h"),
    ("media/libcubeb/src/cubeb_resampler_internal.h", "mozilla/media/libcubeb/src/cubeb_resampler_internal.h"),
    ("media/libcubeb/src/cubeb_ring_array.h", "mozilla/media/libcubeb/src/cubeb_ring_array.h"),
    ("media/libcubeb/src/cubeb_ringbuffer.h", "mozilla/media/libcubeb/src/cubeb_ringbuffer.h"),
    ("media/libcubeb/src/cubeb_strings.h", "mozilla/media/libcubeb/src/cubeb_strings.h"),
    ("media/libcubeb/src/cubeb_utils.h", "mozilla/media/libcubeb/src/cubeb_utils.h"),
    ("media/libcubeb/src/cubeb_utils_unix.h", "mozilla/media/libcubeb/src/cubeb_utils_unix.h"),
    ("media/libcubeb/src/cubeb_utils_win.h", "mozilla/media/libcubeb/src/cubeb_utils_win.h"),
    ("media/libopus/celt/_kiss_fft_guts.h", "mozilla/media/libopus/celt/_kiss_fft_guts.h"),
    ("media/libopus/celt/arch.h", "mozilla/media/libopus/celt/arch.h"),
    ("media/libopus/celt/arm/armcpu.h", "mozilla/media/libopus/celt/arm/armcpu.h"),
    ("media/libopus/celt/arm/fft_arm.h", "mozilla/media/libopus/celt/arm/fft_arm.h"),
    ("media/libopus/celt/arm/fixed_arm64.h", "mozilla/media/libopus/celt/arm/fixed_arm64.h"),
    ("media/libopus/celt/arm/fixed_armv4.h", "mozilla/media/libopus/celt/arm/fixed_armv4.h"),
    ("media/libopus/celt/arm/fixed_armv5e.h", "mozilla/media/libopus/celt/arm/fixed_armv5e.h"),
    ("media/libopus/celt/arm/kiss_fft_armv4.h", "mozilla/media/libopus/celt/arm/kiss_fft_armv4.h"),
    ("media/libopus/celt/arm/kiss_fft_armv5e.h", "mozilla/media/libopus/celt/arm/kiss_fft_armv5e.h"),
    ("media/libopus/celt/arm/mdct_arm.h", "mozilla/media/libopus/celt/arm/mdct_arm.h"),
    ("media/libopus/celt/arm/pitch_arm.h", "mozilla/media/libopus/celt/arm/pitch_arm.h"),
    ("media/libopus/celt/bands.h", "mozilla/media/libopus/celt/bands.h"),
    ("media/libopus/celt/celt.h", "mozilla/media/libopus/celt/celt.h"),
    ("media/libopus/celt/celt_lpc.h", "mozilla/media/libopus/celt/celt_lpc.h"),
    ("media/libopus/celt/cpu_support.h", "mozilla/media/libopus/celt/cpu_support.h"),
    ("media/libopus/celt/cwrs.h", "mozilla/media/libopus/celt/cwrs.h"),
    ("media/libopus/celt/ecintrin.h", "mozilla/media/libopus/celt/ecintrin.h"),
    ("media/libopus/celt/entcode.h", "mozilla/media/libopus/celt/entcode.h"),
    ("media/libopus/celt/entdec.h", "mozilla/media/libopus/celt/entdec.h"),
    ("media/libopus/celt/entenc.h", "mozilla/media/libopus/celt/entenc.h"),
    ("media/libopus/celt/fixed_debug.h", "mozilla/media/libopus/celt/fixed_debug.h"),
    ("media/libopus/celt/fixed_generic.h", "mozilla/media/libopus/celt/fixed_generic.h"),
    ("media/libopus/celt/float_cast.h", "mozilla/media/libopus/celt/float_cast.h"),
    ("media/libopus/celt/kiss_fft.h", "mozilla/media/libopus/celt/kiss_fft.h"),
    ("media/libopus/celt/laplace.h", "mozilla/media/libopus/celt/laplace.h"),
    ("media/libopus/celt/mathops.h", "mozilla/media/libopus/celt/mathops.h"),
    ("media/libopus/celt/mdct.h", "mozilla/media/libopus/celt/mdct.h"),
    ("media/libopus/celt/mfrngcod.h", "mozilla/media/libopus/celt/mfrngcod.h"),
    ("media/libopus/celt/mips/celt_mipsr1.h", "mozilla/media/libopus/celt/mips/celt_mipsr1.h"),
    ("media/libopus/celt/mips/fixed_generic_mipsr1.h", "mozilla/media/libopus/celt/mips/fixed_generic_mipsr1.h"),
    ("media/libopus/celt/mips/kiss_fft_mipsr1.h", "mozilla/media/libopus/celt/mips/kiss_fft_mipsr1.h"),
    ("media/libopus/celt/mips/mdct_mipsr1.h", "mozilla/media/libopus/celt/mips/mdct_mipsr1.h"),
    ("media/libopus/celt/mips/pitch_mipsr1.h", "mozilla/media/libopus/celt/mips/pitch_mipsr1.h"),
    ("media/libopus/celt/mips/vq_mipsr1.h", "mozilla/media/libopus/celt/mips/vq_mipsr1.h"),
    ("media/libopus/celt/modes.h", "mozilla/media/libopus/celt/modes.h"),
    ("media/libopus/celt/os_support.h", "mozilla/media/libopus/celt/os_support.h"),
    ("media/libopus/celt/pitch.h", "mozilla/media/libopus/celt/pitch.h"),
    ("media/libopus/celt/quant_bands.h", "mozilla/media/libopus/celt/quant_bands.h"),
    ("media/libopus/celt/rate.h", "mozilla/media/libopus/celt/rate.h"),
    ("media/libopus/celt/stack_alloc.h", "mozilla/media/libopus/celt/stack_alloc.h"),
    ("media/libopus/celt/static_modes_fixed.h", "mozilla/media/libopus/celt/static_modes_fixed.h"),
    ("media/libopus/celt/static_modes_fixed_arm_ne10.h", "mozilla/media/libopus/celt/static_modes_fixed_arm_ne10.h"),
    ("media/libopus/celt/static_modes_float.h", "mozilla/media/libopus/celt/static_modes_float.h"),
    ("media/libopus/celt/static_modes_float_arm_ne10.h", "mozilla/media/libopus/celt/static_modes_float_arm_ne10.h"),
    ("media/libopus/celt/vq.h", "mozilla/media/libopus/celt/vq.h"),
    ("media/libopus/celt/x86/celt_lpc_sse.h", "mozilla/media/libopus/celt/x86/celt_lpc_sse.h"),
    ("media/libopus/celt/x86/pitch_sse.h", "mozilla/media/libopus/celt/x86/pitch_sse.h"),
    ("media/libopus/celt/x86/vq_sse.h", "mozilla/media/libopus/celt/x86/vq_sse.h"),
    ("media/libopus/celt/x86/x86cpu.h", "mozilla/media/libopus/celt/x86/x86cpu.h"),
    ("media/libopus/include/opus.h", "mozilla/media/libopus/include/opus.h"),
    ("media/libopus/include/opus_custom.h", "mozilla/media/libopus/include/opus_custom.h"),
    ("media/libopus/include/opus_defines.h", "mozilla/media/libopus/include/opus_defines.h"),
    ("media/libopus/include/opus_multistream.h", "mozilla/media/libopus/include/opus_multistream.h"),
    ("media/libopus/include/opus_types.h", "mozilla/media/libopus/include/opus_types.h"),
    ("media/libopus/silk/API.h", "mozilla/media/libopus/silk/API.h"),
    ("media/libopus/silk/arm/biquad_alt_arm.h", "mozilla/media/libopus/silk/arm/biquad_alt_arm.h"),
    ("media/libopus/silk/arm/LPC_inv_pred_gain_arm.h", "mozilla/media/libopus/silk/arm/LPC_inv_pred_gain_arm.h"),
    ("media/libopus/silk/arm/macros_arm64.h", "mozilla/media/libopus/silk/arm/macros_arm64.h"),
    ("media/libopus/silk/arm/macros_armv4.h", "mozilla/media/libopus/silk/arm/macros_armv4.h"),
    ("media/libopus/silk/arm/macros_armv5e.h", "mozilla/media/libopus/silk/arm/macros_armv5e.h"),
    ("media/libopus/silk/arm/NSQ_del_dec_arm.h", "mozilla/media/libopus/silk/arm/NSQ_del_dec_arm.h"),
    ("media/libopus/silk/arm/NSQ_neon.h", "mozilla/media/libopus/silk/arm/NSQ_neon.h"),
    ("media/libopus/silk/arm/SigProc_FIX_armv4.h", "mozilla/media/libopus/silk/arm/SigProc_FIX_armv4.h"),
    ("media/libopus/silk/arm/SigProc_FIX_armv5e.h", "mozilla/media/libopus/silk/arm/SigProc_FIX_armv5e.h"),
    ("media/libopus/silk/control.h", "mozilla/media/libopus/silk/control.h"),
    ("media/libopus/silk/debug.h", "mozilla/media/libopus/silk/debug.h"),
    ("media/libopus/silk/define.h", "mozilla/media/libopus/silk/define.h"),
    ("media/libopus/silk/errors.h", "mozilla/media/libopus/silk/errors.h"),
    ("media/libopus/silk/fixed/arm/warped_autocorrelation_FIX_arm.h", "mozilla/media/libopus/silk/fixed/arm/warped_autocorrelation_FIX_arm.h"),
    ("media/libopus/silk/fixed/main_FIX.h", "mozilla/media/libopus/silk/fixed/main_FIX.h"),
    ("media/libopus/silk/fixed/mips/noise_shape_analysis_FIX_mipsr1.h", "mozilla/media/libopus/silk/fixed/mips/noise_shape_analysis_FIX_mipsr1.h"),
    ("media/libopus/silk/fixed/mips/warped_autocorrelation_FIX_mipsr1.h", "mozilla/media/libopus/silk/fixed/mips/warped_autocorrelation_FIX_mipsr1.h"),
    ("media/libopus/silk/fixed/structs_FIX.h", "mozilla/media/libopus/silk/fixed/structs_FIX.h"),
    ("media/libopus/silk/float/main_FLP.h", "mozilla/media/libopus/silk/float/main_FLP.h"),
    ("media/libopus/silk/float/SigProc_FLP.h", "mozilla/media/libopus/silk/float/SigProc_FLP.h"),
    ("media/libopus/silk/float/structs_FLP.h", "mozilla/media/libopus/silk/float/structs_FLP.h"),
    ("media/libopus/silk/Inlines.h", "mozilla/media/libopus/silk/Inlines.h"),
    ("media/libopus/silk/MacroCount.h", "mozilla/media/libopus/silk/MacroCount.h"),
    ("media/libopus/silk/MacroDebug.h", "mozilla/media/libopus/silk/MacroDebug.h"),
    ("media/libopus/silk/macros.h", "mozilla/media/libopus/silk/macros.h"),
    ("media/libopus/silk/main.h", "mozilla/media/libopus/silk/main.h"),
    ("media/libopus/silk/mips/macros_mipsr1.h", "mozilla/media/libopus/silk/mips/macros_mipsr1.h"),
    ("media/libopus/silk/mips/NSQ_del_dec_mipsr1.h", "mozilla/media/libopus/silk/mips/NSQ_del_dec_mipsr1.h"),
    ("media/libopus/silk/mips/sigproc_fix_mipsr1.h", "mozilla/media/libopus/silk/mips/sigproc_fix_mipsr1.h"),
    ("media/libopus/silk/NSQ.h", "mozilla/media/libopus/silk/NSQ.h"),
    ("media/libopus/silk/pitch_est_defines.h", "mozilla/media/libopus/silk/pitch_est_defines.h"),
    ("media/libopus/silk/PLC.h", "mozilla/media/libopus/silk/PLC.h"),
    ("media/libopus/silk/resampler_private.h", "mozilla/media/libopus/silk/resampler_private.h"),
    ("media/libopus/silk/resampler_rom.h", "mozilla/media/libopus/silk/resampler_rom.h"),
    ("media/libopus/silk/resampler_structs.h", "mozilla/media/libopus/silk/resampler_structs.h"),
    ("media/libopus/silk/SigProc_FIX.h", "mozilla/media/libopus/silk/SigProc_FIX.h"),
    ("media/libopus/silk/structs.h", "mozilla/media/libopus/silk/structs.h"),
    ("media/libopus/silk/tables.h", "mozilla/media/libopus/silk/tables.h"),
    ("media/libopus/silk/tuning_parameters.h", "mozilla/media/libopus/silk/tuning_parameters.h"),
    ("media/libopus/silk/typedef.h", "mozilla/media/libopus/silk/typedef.h"),
    ("media/libopus/silk/x86/main_sse.h", "mozilla/media/libopus/silk/x86/main_sse.h"),
    ("media/libopus/silk/x86/SigProc_FIX_sse.h", "mozilla/media/libopus/silk/x86/SigProc_FIX_sse.h"),
    ("media/libopus/src/analysis.h", "mozilla/media/libopus/src/analysis.h"),
    ("media/libopus/src/mlp.h", "mozilla/media/libopus/src/mlp.h"),
    ("media/libopus/src/opus_private.h", "mozilla/media/libopus/src/opus_private.h"),
    ("media/libopus/src/tansig_table.h", "mozilla/media/libopus/src/tansig_table.h"),
    ("media/libvorbis/lib/backends.h", "mozilla/media/libvorbis/lib/backends.h"),
    ("media/libvorbis/lib/bitrate.h", "mozilla/media/libvorbis/lib/bitrate.h"),
    ("media/libvorbis/lib/books/coupled/res_books_51.h", "mozilla/media/libvorbis/lib/books/coupled/res_books_51.h"),
    ("media/libvorbis/lib/books/coupled/res_books_stereo.h", "mozilla/media/libvorbis/lib/books/coupled/res_books_stereo.h"),
    ("media/libvorbis/lib/books/floor/floor_books.h", "mozilla/media/libvorbis/lib/books/floor/floor_books.h"),
    ("media/libvorbis/lib/books/uncoupled/res_books_uncoupled.h", "mozilla/media/libvorbis/lib/books/uncoupled/res_books_uncoupled.h"),
    ("media/libvorbis/lib/codebook.h", "mozilla/media/libvorbis/lib/codebook.h"),
    ("media/libvorbis/lib/codec_internal.h", "mozilla/media/libvorbis/lib/codec_internal.h"),
    ("media/libvorbis/lib/envelope.h", "mozilla/media/libvorbis/lib/envelope.h"),
    ("media/libvorbis/lib/highlevel.h", "mozilla/media/libvorbis/lib/highlevel.h"),
    ("media/libvorbis/lib/lookup.h", "mozilla/media/libvorbis/lib/lookup.h"),
    ("media/libvorbis/lib/lookup_data.h", "mozilla/media/libvorbis/lib/lookup_data.h"),
    ("media/libvorbis/lib/lpc.h", "mozilla/media/libvorbis/lib/lpc.h"),
    ("media/libvorbis/lib/lsp.h", "mozilla/media/libvorbis/lib/lsp.h"),
    ("media/libvorbis/lib/masking.h", "mozilla/media/libvorbis/lib/masking.h"),
    ("media/libvorbis/lib/mdct.h", "mozilla/media/libvorbis/lib/mdct.h"),
    ("media/libvorbis/lib/misc.h", "mozilla/media/libvorbis/lib/misc.h"),
    ("media/libvorbis/lib/modes/floor_all.h", "mozilla/media/libvorbis/lib/modes/floor_all.h"),
    ("media/libvorbis/lib/modes/psych_11.h", "mozilla/media/libvorbis/lib/modes/psych_11.h"),
    ("media/libvorbis/lib/modes/psych_16.h", "mozilla/media/libvorbis/lib/modes/psych_16.h"),
    ("media/libvorbis/lib/modes/psych_44.h", "mozilla/media/libvorbis/lib/modes/psych_44.h"),
    ("media/libvorbis/lib/modes/psych_8.h", "mozilla/media/libvorbis/lib/modes/psych_8.h"),
    ("media/libvorbis/lib/modes/residue_16.h", "mozilla/media/libvorbis/lib/modes/residue_16.h"),
    ("media/libvorbis/lib/modes/residue_44.h", "mozilla/media/libvorbis/lib/modes/residue_44.h"),
    ("media/libvorbis/lib/modes/residue_44p51.h", "mozilla/media/libvorbis/lib/modes/residue_44p51.h"),
    ("media/libvorbis/lib/modes/residue_44u.h", "mozilla/media/libvorbis/lib/modes/residue_44u.h"),
    ("media/libvorbis/lib/modes/residue_8.h", "mozilla/media/libvorbis/lib/modes/residue_8.h"),
    ("media/libvorbis/lib/modes/setup_11.h", "mozilla/media/libvorbis/lib/modes/setup_11.h"),
    ("media/libvorbis/lib/modes/setup_16.h", "mozilla/media/libvorbis/lib/modes/setup_16.h"),
    ("media/libvorbis/lib/modes/setup_22.h", "mozilla/media/libvorbis/lib/modes/setup_22.h"),
    ("media/libvorbis/lib/modes/setup_32.h", "mozilla/media/libvorbis/lib/modes/setup_32.h"),
    ("media/libvorbis/lib/modes/setup_44.h", "mozilla/media/libvorbis/lib/modes/setup_44.h"),
    ("media/libvorbis/lib/modes/setup_44p51.h", "mozilla/media/libvorbis/lib/modes/setup_44p51.h"),
    ("media/libvorbis/lib/modes/setup_44u.h", "mozilla/media/libvorbis/lib/modes/setup_44u.h"),
    ("media/libvorbis/lib/modes/setup_8.h", "mozilla/media/libvorbis/lib/modes/setup_8.h"),
    ("media/libvorbis/lib/modes/setup_X.h", "mozilla/media/libvorbis/lib/modes/setup_X.h"),
    ("media/libvorbis/lib/os.h", "mozilla/media/libvorbis/lib/os.h"),
    ("media/libvorbis/lib/psy.h", "mozilla/media/libvorbis/lib/psy.h"),
    ("media/libvorbis/lib/registry.h", "mozilla/media/libvorbis/lib/registry.h"),
    ("media/libvorbis/lib/scales.h", "mozilla/media/libvorbis/lib/scales.h"),
    ("media/libvorbis/lib/smallft.h", "mozilla/media/libvorbis/lib/smallft.h"),
    ("media/libvorbis/lib/window.h", "mozilla/media/libvorbis/lib/window.h"),
    ("memory/build/malloc_decls.h", "malloc_decls.h"),
    ("memory/build/mozjemalloc_types.h", "mozjemalloc_types.h"),
    ("memory/build/mozmemory_wrap.h", "mozmemory_wrap.h"),
    ("memory/fallible/fallible.h", "mozilla/fallible.h"),
    ("memory/mozalloc/mozalloc.h", "mozilla/mozalloc.h"),
    ("memory/mozalloc/mozalloc_abort.h", "mozilla/mozalloc_abort.h"),
    ("memory/mozalloc/mozalloc_oom.h", "mozilla/mozalloc_oom.h"),
    ("memory/mozalloc/throw_gcc.h", "mozilla/throw_gcc.h"),
    ("mfbt/Alignment.h", "mozilla/Alignment.h"),
    ("mfbt/AllocPolicy.h", "mozilla/AllocPolicy.h"),
    ("mfbt/AlreadyAddRefed.h", "mozilla/AlreadyAddRefed.h"),
    ("mfbt/Array.h", "mozilla/Array.h"),
    ("mfbt/ArrayUtils.h", "mozilla/ArrayUtils.h"),
    ("mfbt/Atomics.h", "mozilla/Atomics.h"),
    ("mfbt/Attributes.h", "mozilla/Attributes.h"),
    ("mfbt/BinarySearch.h", "mozilla/BinarySearch.h"),
    ("mfbt/BufferList.h", "mozilla/BufferList.h"),
    ("mfbt/Casting.h", "mozilla/Casting.h"),
    ("mfbt/Char16.h", "mozilla/Char16.h"),
    ("mfbt/ChaosMode.h", "mozilla/ChaosMode.h"),
    ("mfbt/CheckedInt.h", "mozilla/CheckedInt.h"),
    ("mfbt/Compiler.h", "mozilla/Compiler.h"),
    ("mfbt/DebugOnly.h", "mozilla/DebugOnly.h"),
    ("mfbt/DefineEnum.h", "mozilla/DefineEnum.h"),
    ("mfbt/double-conversion/source/double-conversion.h", "mozilla/double-conversion.h"),
    ("mfbt/double-conversion/source/utils.h", "mozilla/double-conversion/utils.h"),
    ("mfbt/EndianUtils.h", "mozilla/EndianUtils.h"),
    ("mfbt/EnumeratedArray.h", "mozilla/EnumeratedArray.h"),
    ("mfbt/EnumSet.h", "mozilla/EnumSet.h"),
    ("mfbt/FloatingPoint.h", "mozilla/FloatingPoint.h"),
    ("mfbt/GuardObjects.h", "mozilla/GuardObjects.h"),
    ("mfbt/HashFunctions.h", "mozilla/HashFunctions.h"),
    ("mfbt/IndexSequence.h", "mozilla/IndexSequence.h"),
    ("mfbt/IndexSequence.h", "mozilla/IndexSequence.h"),
    ("mfbt/IntegerPrintfMacros.h", "mozilla/IntegerPrintfMacros.h"),
    ("mfbt/IntegerPrintfMacros.h", "mozilla/IntegerPrintfMacros.h"),
    ("mfbt/IntegerTypeTraits.h", "mozilla/IntegerTypeTraits.h"),
    ("mfbt/IntegerTypeTraits.h", "mozilla/IntegerTypeTraits.h"),
    ("mfbt/Likely.h", "mozilla/Likely.h"),
    ("mfbt/LinkedList.h", "mozilla/LinkedList.h"),
    ("mfbt/MacroArgs.h", "mozilla/MacroArgs.h"),
    ("mfbt/MacroForEach.h", "mozilla/MacroForEach.h"),
    ("mfbt/MathAlgorithms.h", "mozilla/MathAlgorithms.h"),
    ("mfbt/Maybe.h", "mozilla/Maybe.h"),
    ("mfbt/MemoryChecking.h", "mozilla/MemoryChecking.h"),
    ("mfbt/MemoryReporting.h", "mozilla/MemoryReporting.h"),
    ("mfbt/Move.h", "mozilla/Move.h"),
    ("mfbt/NotNull.h", "mozilla/NotNull.h"),
    ("mfbt/Opaque.h", "mozilla/Opaque.h"),
    ("mfbt/OperatorNewExtensions.h", "mozilla/OperatorNewExtensions.h"),
    ("mfbt/Pair.h", "mozilla/Pair.h"),
    ("mfbt/PodOperations.h", "mozilla/PodOperations.h"),
    ("mfbt/Range.h", "mozilla/Range.h"),
    ("mfbt/RangedPtr.h", "mozilla/RangedPtr.h"),
    ("mfbt/ReentrancyGuard.h", "mozilla/ReentrancyGuard.h"),
    ("mfbt/RefCounted.h", "mozilla/RefCounted.h"),
    ("mfbt/RefCountType.h", "mozilla/RefCountType.h"),
    ("mfbt/RefPtr.h", "mozilla/RefPtr.h"),
    ("mfbt/Result.h", "mozilla/Result.h"),
    ("mfbt/ReverseIterator.h", "mozilla/ReverseIterator.h"),
    ("mfbt/Scoped.h", "mozilla/Scoped.h"),
    ("mfbt/ScopeExit.h", "mozilla/ScopeExit.h"),
    ("mfbt/Span.h", "mozilla/Span.h"),
    ("mfbt/Sprintf.h", "mozilla/Sprintf.h"),
    ("mfbt/StaticAnalysisFunctions.h", "mozilla/StaticAnalysisFunctions.h"),
    ("mfbt/TaggedAnonymousMemory.h", "mozilla/TaggedAnonymousMemory.h"),
    ("mfbt/TemplateLib.h", "mozilla/TemplateLib.h"),
    ("mfbt/ThreadLocal.h", "mozilla/ThreadLocal.h"),
    ("mfbt/Tuple.h", "mozilla/Tuple.h"),
    ("mfbt/TypedEnumBits.h", "mozilla/TypedEnumBits.h"),
    ("mfbt/Types.h", "mozilla/Types.h"),
    ("mfbt/TypeTraits.h", "mozilla/TypeTraits.h"),
    ("mfbt/UniquePtr.h", "mozilla/UniquePtr.h"),
    ("mfbt/UniquePtrExtensions.h", "mozilla/UniquePtrExtensions.h"),
    ("mfbt/Unused.h", "mozilla/Unused.h"),
    ("mfbt/Variant.h", "mozilla/Variant.h"),
    ("mfbt/Vector.h", "mozilla/Vector.h"),
    ("mfbt/WeakPtr.h", "mozilla/WeakPtr.h"),
    ("mozglue/build/arm.h", "mozilla/arm.h"),
    ("mozglue/build/SSE.h", "mozilla/SSE.h"),
    ("mozglue/misc/MutexPlatformData_posix.h", "MutexPlatformData_posix.h"),
    ("mozglue/misc/PlatformConditionVariable.h", "mozilla/PlatformConditionVariable.h"),
    ("mozglue/misc/PlatformMutex.h", "mozilla/PlatformMutex.h"),
    ("mozglue/misc/Printf.h", "mozilla/Printf.h"),
    ("mozglue/misc/TimeStamp_windows.h", "mozilla/TimeStamp_windows.h"),
    ("mozglue/misc/TimeStamp.h", "mozilla/TimeStamp.h"),
    ("nsprpub/pr/include/nspr.h", "nspr.h"),
    ("nsprpub/pr/include/obsolete/probslet.h", "nspr/obsolete/probslet.h"),
    ("nsprpub/pr/include/obsolete/protypes.h", "nspr/obsolete/protypes.h"),
    ("nsprpub/pr/include/obsolete/prsem.h", "nspr/obsolete/prsem.h"),
    ("nsprpub/pr/include/pratom.h", "pratom.h"),
    ("nsprpub/pr/include/prbit.h", "prbit.h"),
    ("nsprpub/pr/include/prclist.h", "prclist.h"),
    ("nsprpub/pr/include/prcmon.h", "prcmon.h"),
    ("nsprpub/pr/include/prcvar.h", "prcvar.h"),
    ("nsprpub/pr/include/prdtoa.h", "prdtoa.h"),
    ("nsprpub/pr/include/prerr.h", "prerr.h"),
    ("nsprpub/pr/include/prerror.h", "prerror.h"),
    ("nsprpub/pr/include/pripcsem.h", "pripcsem.h"),
    ("nsprpub/pr/include/private/pprio.h", "nspr/private/pprio.h"),
    ("nsprpub/pr/include/private/pprmwait.h", "nspr/private/pprmwait.h"),
    ("nsprpub/pr/include/private/pprthred.h", "nspr/private/pprthred.h"),
    ("nsprpub/pr/include/private/primpl.h", "nspr/private/primpl.h"),
    ("nsprpub/pr/include/private/prpriv.h", "nspr/private/prpriv.h"),
    ("nsprpub/pr/include/prpdce.h", "prpdce.h"),
    ("media/libogg/include/ogg/config_types.h", "mozilla/media/libogg/include/ogg/config_types.h"),
    ("media/libogg/include/ogg/ogg.h", "mozilla/media/libogg/include/ogg/ogg.h"),
    ("media/libogg/include/ogg/os_types.h", "mozilla/media/libogg/include/ogg/os_types.h"),
    ('media/libsoundtouch/src/AAFilter.h', 'mozilla/media/libsoundtouch/src/AAFilter.h'),
    ('media/libsoundtouch/src/cpu_detect.h', 'mozilla/media/libsoundtouch/src/cpu_detect.h'),
    ('media/libsoundtouch/src/FIFOSampleBuffer.h', 'mozilla/media/libsoundtouch/src/FIFOSampleBuffer.h'),
    ('media/libsoundtouch/src/FIFOSamplePipe.h', 'mozilla/media/libsoundtouch/src/FIFOSamplePipe.h'),
    ('media/libsoundtouch/src/FIRFilter.h', 'mozilla/media/libsoundtouch/src/FIRFilter.h'),
    ('media/libsoundtouch/src/InterpolateCubic.h', 'mozilla/media/libsoundtouch/src/InterpolateCubic.h'),
    ('media/libsoundtouch/src/InterpolateLinear.h', 'mozilla/media/libsoundtouch/src/InterpolateLinear.h'),
    ('media/libsoundtouch/src/InterpolateShannon.h', 'mozilla/media/libsoundtouch/src/InterpolateShannon.h'),
    ('media/libsoundtouch/src/RateTransposer.h', 'mozilla/media/libsoundtouch/src/RateTransposer.h'),
    ('media/libsoundtouch/src/SoundTouch.h', 'mozilla/media/libsoundtouch/src/SoundTouch.h'),
    ('media/libsoundtouch/src/soundtouch_config.h', 'mozilla/media/libsoundtouch/src/soundtouch_config.h'),
    ('media/libsoundtouch/src/soundtouch_perms.h', 'mozilla/media/libsoundtouch/src/soundtouch_perms.h'),
    ('media/libsoundtouch/src/STTypes.h', 'mozilla/media/libsoundtouch/src/STTypes.h'),
    ('media/libsoundtouch/src/TDStretch.h', 'mozilla/media/libsoundtouch/src/TDStretch.h'),
    ('media/libspeex_resampler/src/arch.h', 'mozilla/media/libspeex_resampler/src/arch.h'),
    ('media/libspeex_resampler/src/fixed_generic.h', 'mozilla/media/libspeex_resampler/src/fixed_generic.h'),
    ('media/libspeex_resampler/src/simd_detect.h', 'mozilla/media/libspeex_resampler/src/simd_detect.h'),
    ('media/libspeex_resampler/src/speex_resampler.h', 'mozilla/media/libspeex_resampler/src/speex_resampler.h'),
    ('media/libspeex_resampler/src/stack_alloc.h', 'mozilla/media/libspeex_resampler/src/stack_alloc.h'),
    ("nsprpub/pr/include/prlink.h", "prlink.h"),
    ("nsprpub/pr/include/prlock.h", "prlock.h"),
    ("nsprpub/pr/include/prlog.h", "prlog.h"),
    ("nsprpub/pr/include/prlong.h", "prlong.h"),
    ("nsprpub/pr/include/prmem.h", "prmem.h"),
    ("nsprpub/pr/include/prmon.h", "prmon.h"),
    ("nsprpub/pr/include/prmwait.h", "prmwait.h"),
    ("nsprpub/pr/include/prnetdb.h", "prnetdb.h"),
    ("nsprpub/pr/include/prproces.h", "prproces.h"),
    ("nsprpub/pr/include/prrng.h", "prrng.h"),
    ("nsprpub/pr/include/prrwlock.h", "prrwlock.h"),
    ("nsprpub/pr/include/prshm.h", "prshm.h"),
    ("nsprpub/pr/include/prshma.h", "prshma.h"),
    ("nsprpub/pr/include/prsystem.h", "prsystem.h"),
    ("nsprpub/pr/include/prtime.h", "prtime.h"),
    ("nsprpub/pr/include/prtpool.h", "prtpool.h"),
    ("nsprpub/pr/include/prtrace.h", "prtrace.h"),
    ("nsprpub/pr/include/prtypes.h", "prtypes.h"),
    ("nsprpub/lib/libc/include/plstr.h", "plstr.h"),
    # TODO: import more cfg files as needed.
    ("nsprpub/pr/include/md/_darwin.cfg", "md/_darwin.cfg"),
    ("nsprpub/pr/include/md/_darwin.h", "md/_darwin.h"),
    ("nsprpub/pr/include/md/_linux.cfg", "md/_linux.cfg"),
    ("nsprpub/pr/include/md/_linux.h", "md/_linux.h"),
    ("nsprpub/pr/include/md/_pth.h", "md/_pth.h"),
    ("nsprpub/pr/include/md/_unix_errors.h", "md/_unix_errors.h"),
    ("nsprpub/pr/include/md/_unixos.h", "md/_unixos.h"),
    ("nsprpub/pr/include/md/prosdep.h", "md/prosdep.h"),
    ("toolkit/components/startup/StartupTimeline.h", "mozilla/StartupTimeline.h"),
    ("toolkit/components/telemetry/Telemetry.h", "mozilla/Telemetry.h"),
    ("toolkit/crashreporter/nsExceptionHandler.h", "nsExceptionHandler.h"),
    ("toolkit/crashreporter/ThreadAnnotation.h", "ThreadAnnotation.h"),
    ("xpcom/base/ClearOnShutdown.h", "mozilla/ClearOnShutdown.h"),
    ("xpcom/base/DeferredFinalize.h", "mozilla/DeferredFinalize.h"),
    ("xpcom/base/ErrorNames.h", "mozilla/ErrorNames.h"),
    ("xpcom/base/Logging.h", "mozilla/Logging.h"),
    ("xpcom/base/nsAlgorithm.h", "nsAlgorithm.h"),
    ("xpcom/base/nsAutoRef.h", "nsAutoRef.h"),
    ("xpcom/base/nscore.h", "nscore.h"),
    ("xpcom/base/nsCRTGlue.h", "nsCRTGlue.h"),
    ("xpcom/base/nsCycleCollectionParticipant.h", "nsCycleCollectionParticipant.h"),
    ("xpcom/base/nsCycleCollectionTraversalCallback.h", "nsCycleCollectionTraversalCallback.h"),
    ("xpcom/base/nsDebug.h", "nsDebug.h"),
    ("xpcom/base/nsError.h", "nsError.h"),
    ("xpcom/base/nsID.h", "nsID.h"),
    ("xpcom/base/nsIClassInfoImpl.h", "nsIClassInfoImpl.h"),
    ("xpcom/base/nsIInterfaceRequestorUtils.h", "nsIInterfaceRequestorUtils.h"),
    ("xpcom/base/nsISupportsBase.h", "nsISupportsBase.h"),
    ("xpcom/base/nsISupportsImpl.h", "nsISupportsImpl.h"),
    ("xpcom/base/nsISupportsUtils.h", "nsISupportsUtils.h"),
    ("xpcom/base/nsIWeakReferenceUtils.h", "nsIWeakReferenceUtils.h"),
    ("xpcom/base/nsMemory.h", "nsMemory.h"),
    ("xpcom/base/NSPRLogModulesParser.h", "NSPRLogModulesParser.h"),
    ("xpcom/base/nsQueryObject.h", "nsQueryObject.h"),
    ("xpcom/base/nsTraceRefcnt.h", "nsTraceRefcnt.h"),
    ("xpcom/base/nsWeakReference.h", "nsWeakReference.h"),
    ("xpcom/base/StaticMutex.h", "mozilla/StaticMutex.h"),
    ("xpcom/base/StaticPtr.h", "mozilla/StaticPtr.h"),
    ("xpcom/build/IOInterposer.h", "mozilla/IOInterposer.h"),
    ("xpcom/build/nsXPCOM.h", "nsXPCOM.h"),
    ("xpcom/build/nsXPCOMCID.h", "nsXPCOMCID.h"),
    ("xpcom/build/nsXPCOMCIDInternal.h", "nsXPCOMCIDInternal.h"),
    ("xpcom/build/nsXPCOMPrivate.h", "nsXPCOMPrivate.h"),
    ("xpcom/build/Services.h", "mozilla/Services.h"),
    ("xpcom/build/XREAppData.h", "mozilla/XREAppData.h"),
    ("xpcom/build/XREChildData.h", "XREChildData.h"),
    ("xpcom/build/xrecore.h", "xrecore.h"),
    ("xpcom/build/XREShellData.h", "XREShellData.h"),
    ("xpcom/components/GenericFactory.h", "mozilla/GenericFactory.h"),
    ("xpcom/components/Module.h", "mozilla/Module.h"),
    ("xpcom/components/ModuleUtils.h", "mozilla/ModuleUtils.h"),
    ("xpcom/components/nsCategoryManager.h", "nsCategoryManager.h"),
    ("xpcom/components/nsCategoryManagerUtils.h", "nsCategoryManagerUtils.h"),
    ("xpcom/components/nsComponentManagerUtils.h", "nsComponentManagerUtils.h"),
    ("xpcom/components/nsServiceManagerUtils.h", "nsServiceManagerUtils.h"),
    ("xpcom/ds/ArenaAllocator.h", "mozilla/ArenaAllocator.h"),
    ("xpcom/ds/ArenaAllocatorExtensions.h", "mozilla/ArenaAllocatorExtensions.h"),
    ("xpcom/ds/ArrayIterator.h", "mozilla/ArrayIterator.h"),
    ("xpcom/ds/nsArrayEnumerator.h", "nsArrayEnumerator.h"),
    ("xpcom/ds/nsBaseHashtable.h", "nsBaseHashtable.h"),
    ("xpcom/ds/nsClassHashtable.h", "nsClassHashtable.h"),
    ("xpcom/ds/nsCRT.h", "nsCRT.h"),
    ("xpcom/ds/nsDataHashtable.h", "nsDataHashtable.h"),
    ("xpcom/ds/nsEnumeratorUtils.h", "nsEnumeratorUtils.h"),
    ("xpcom/ds/nsHashKeys.h", "nsHashKeys.h"),
    ("xpcom/ds/nsInterfaceHashtable.h", "nsInterfaceHashtable.h"),
    ("xpcom/ds/nsMathUtils.h", "nsMathUtils.h"),
    ("xpcom/ds/nsObserverList.h", "nsObserverList.h"),
    ("xpcom/ds/nsObserverService.h", "nsObserverService.h"),
    ("xpcom/ds/nsPointerHashKeys.h", "nsPointerHashKeys.h"),
    ("xpcom/ds/nsQuickSort.h", "nsQuickSort.h"),
    ("xpcom/ds/nsRefPtrHashtable.h", "nsRefPtrHashtable.h"),
    ("xpcom/ds/nsStringEnumerator.h", "nsStringEnumerator.h"),
    ("xpcom/ds/nsSupportsPrimitives.h", "nsSupportsPrimitives.h"),
    ("xpcom/ds/nsTHashtable.h", "nsTHashtable.h"),
    ("xpcom/ds/PLDHashTable.h", "PLDHashTable.h"),
    ("xpcom/glue/FileUtils.h", "mozilla/FileUtils.h"),
    ("xpcom/glue/nsStringGlue.h", "nsStringGlue.h"),
    ("xpcom/io/nsAppDirectoryServiceDefs.h", "nsAppDirectoryServiceDefs.h"),
    ("xpcom/io/nsAppFileLocationProvider.h", "nsAppFileLocationProvider.h"),
    ("xpcom/io/nsDirectoryService.h", "nsDirectoryService.h"),
    ("xpcom/io/nsDirectoryServiceAtomList.h", "nsDirectoryServiceAtomList.h"),
    ("xpcom/io/nsDirectoryServiceDefs.h", "nsDirectoryServiceDefs.h"),
    ("xpcom/io/nsDirectoryServiceUtils.h", "nsDirectoryServiceUtils.h"),
    ("xpcom/io/nsLocalFile.h", "nsLocalFile.h"),
    ("xpcom/io/nsLocalFileUnix.h", "nsLocalFileUnix.h"),
    ("xpcom/io/SpecialSystemDirectory.h", "SpecialSystemDirectory.h"),
    ("xpcom/reflect/xptinfo/XPTInterfaceInfoManager.h", "mozilla/XPTInterfaceInfoManager.h"),
    ("xpcom/reflect/xptinfo/xptinfo.h", "xptinfo.h"),
    ("xpcom/string/nsASCIIMask.h", "nsASCIIMask.h"),
    ("xpcom/string/nsAString.h", "nsAString.h"),
    ("xpcom/string/nsCharTraits.h", "nsCharTraits.h"),
    ("xpcom/string/nsDependentString.h", "nsDependentString.h"),
    ("xpcom/string/nsDependentSubstring.h", "nsDependentSubstring.h"),
    ("xpcom/string/nsLiteralString.h", "nsLiteralString.h"),
    ("xpcom/string/nsPrintfCString.h", "nsPrintfCString.h"),
    ("xpcom/string/nsPromiseFlatString.h", "nsPromiseFlatString.h"),
    ("xpcom/string/nsReadableUtils.h", "nsReadableUtils.h"),
    ("xpcom/string/nsReadableUtilsImpl.h", "nsReadableUtilsImpl.h"),
    ("xpcom/string/nsString.h", "nsString.h"),
    ("xpcom/string/nsStringBuffer.h", "nsStringBuffer.h"),
    ("xpcom/string/nsStringFlags.h", "nsStringFlags.h"),
    ("xpcom/string/nsStringFwd.h", "nsStringFwd.h"),
    ("xpcom/string/nsStringIterator.h", "nsStringIterator.h"),
    ("xpcom/string/nsSubstring.h", "nsSubstring.h"),
    ("xpcom/string/nsSubstringTuple.h", "nsSubstringTuple.h"),
    ("xpcom/string/nsTDependentString.h", "nsTDependentString.h"),
    ("xpcom/string/nsTDependentSubstring.h", "nsTDependentSubstring.h"),
    ("xpcom/string/nsTLiteralString.h", "nsTLiteralString.h"),
    ("xpcom/string/nsTPromiseFlatString.h", "nsTPromiseFlatString.h"),
    ("xpcom/string/nsTString.h", "nsTString.h"),
    ("xpcom/string/nsTStringRepr.h", "nsTStringRepr.h"),
    ("xpcom/string/nsTSubstring.h", "nsTSubstring.h"),
    ("xpcom/string/nsTSubstringTuple.h", "nsTSubstringTuple.h"),
    ("xpcom/string/nsUTF8Utils.h", "nsUTF8Utils.h"),
    ("xpcom/threads/AbstractEventQueue.h", "mozilla/AbstractEventQueue.h"),
    ("xpcom/threads/AbstractThread.h", "mozilla/AbstractThread.h"),
    ("xpcom/threads/CondVar.h", "mozilla/CondVar.h"),
    ("xpcom/threads/CooperativeThreadPool.h", "mozilla/CooperativeThreadPool.h"),
    ("xpcom/threads/DeadlockDetector.h", "mozilla/DeadlockDetector.h"),
    ("xpcom/threads/EventQueue.h", "mozilla/EventQueue.h"),
    ("xpcom/threads/HangMonitor.h", "mozilla/HangMonitor.h"),
    ("xpcom/threads/InputEventStatistics.h", "InputEventStatistics.h"),
    ("xpcom/threads/LabeledEventQueue.h", "mozilla/LabeledEventQueue.h"),
    ("xpcom/threads/LeakRefPtr.h", "mozilla/LeakRefPtr.h"),
    ("xpcom/threads/MainThreadIdlePeriod.h", "MainThreadIdlePeriod.h"),
    ("xpcom/threads/MainThreadQueue.h", "MainThreadQueue.h"),
    ("xpcom/threads/MainThreadUtils.h", "MainThreadUtils.h"),
    ("xpcom/threads/Monitor.h", "mozilla/Monitor.h"),
    ("xpcom/threads/MozPromise.h", "mozilla/MozPromise.h"),
    ("xpcom/threads/Mutex.h", "mozilla/Mutex.h"),
    ("xpcom/threads/nsICancelableRunnable.h", "nsICancelableRunnable.h"),
    ("xpcom/threads/nsILabelableRunnable.h", "nsILabelableRunnable.h"),
    ("xpcom/threads/nsMemoryPressure.h", "nsMemoryPressure.h"),
    ("xpcom/threads/nsThreadManager.h", "nsThreadManager.h"),
    ("xpcom/threads/nsThreadPool.h", "nsThreadPool.h"),
    ("xpcom/threads/nsThreadUtils.h", "nsThreadUtils.h"),
    ("xpcom/threads/nsThreadSyncDispatch.h", "nsThreadSyncDispatch.h"),
    ("xpcom/threads/nsTimerImpl.h", "nsTimerImpl.h"),
    ("xpcom/threads/PrioritizedEventQueue.h", "PrioritizedEventQueue.h"),
    ("xpcom/threads/Queue.h", "mozilla/Queue.h"),
    ("xpcom/threads/ReentrantMonitor.h", "mozilla/ReentrantMonitor.h"),
    ("xpcom/threads/RecursiveMutex.h", "mozilla/RecursiveMutex.h"),
    ("xpcom/threads/Scheduler.h", "mozilla/Scheduler.h"),
    ("xpcom/threads/SchedulerGroup.h", "mozilla/SchedulerGroup.h"),
    ("xpcom/threads/SharedThreadPool.h", "mozilla/SharedThreadPool.h"),
    ("xpcom/threads/StateWatching.h", "mozilla/StateWatching.h"),
    ("xpcom/threads/SynchronizedEventQueue.h", "mozilla/SynchronizedEventQueue.h"),
    ("xpcom/threads/SystemGroup.h", "mozilla/SystemGroup.h"),
    ("xpcom/threads/TaskCategory.h", "mozilla/TaskCategory.h"),
    ("xpcom/threads/TaskDispatcher.h", "mozilla/TaskDispatcher.h"),
    ("xpcom/threads/TaskQueue.h", "mozilla/TaskQueue.h"),
    ("xpcom/threads/ThreadEventQueue.h", "mozilla/ThreadEventQueue.h"),
    ("xpcom/threads/ThreadEventTarget.h", "mozilla/ThreadEventTarget.h"),
    ("xpcom/threads/TimerThread.h", "TimerThread.h"),
    ("xpcom/threads/RWLock.h", "mozilla/RWLock.h"),
    ("xpcom/typelib/xpt/xpt_arena.h", "xpt_arena.h"),
    ("xpcom/typelib/xpt/xpt_struct.h", "xpt_struct.h"),
    ("xpcom/typelib/xpt/xpt_xdr.h", "xpt_xdr.h"),
]

src_files = [
    "dom/media/AudioStream.cpp",
    "dom/media/CubebUtils.cpp",
    "dom/media/MediaInfo.cpp",
    "dom/media/systemservices/OSXRunLoopSingleton.cpp",
    "media/libcubeb/src/cubeb.c",
    "media/libcubeb/src/cubeb_alsa.c",
    "media/libcubeb/src/cubeb_audiotrack.c",
    "media/libcubeb/src/cubeb_audiounit.cpp",
    "media/libcubeb/src/cubeb_jack.cpp",
    "media/libcubeb/src/cubeb_log.cpp",
    "media/libcubeb/src/cubeb_mixer.cpp",
    "media/libcubeb/src/cubeb_opensl.c",
    "media/libcubeb/src/cubeb_osx_run_loop.c",
    "media/libcubeb/src/cubeb_panner.cpp",
    "media/libcubeb/src/cubeb_pulse.c",
    "media/libcubeb/src/cubeb_resampler.cpp",
    "media/libcubeb/src/cubeb_sndio.c",
    "media/libcubeb/src/cubeb_strings.c",
    "media/libcubeb/src/cubeb_wasapi.cpp",
    "media/libcubeb/src/cubeb_winmm.c",
    "media/libogg/src/ogg_alloc.c",
    "media/libogg/src/ogg_bitwise.c",
    "media/libogg/src/ogg_framing.c",
    "media/libopus/celt/arm/arm_celt_map.c",
    "media/libopus/celt/arm/armcpu.c",
    "media/libopus/celt/arm/celt_ne10_fft.c",
    "media/libopus/celt/arm/celt_ne10_mdct.c",
    "media/libopus/celt/arm/celt_neon_intr.c",
    "media/libopus/celt/arm/pitch_neon_intr.c",
    "media/libopus/celt/bands.c",
    "media/libopus/celt/celt.c",
    "media/libopus/celt/celt_decoder.c",
    "media/libopus/celt/celt_encoder.c",
    "media/libopus/celt/celt_lpc.c",
    "media/libopus/celt/cwrs.c",
    "media/libopus/celt/entcode.c",
    "media/libopus/celt/entdec.c",
    "media/libopus/celt/entenc.c",
    "media/libopus/celt/kiss_fft.c",
    "media/libopus/celt/laplace.c",
    "media/libopus/celt/mathops.c",
    "media/libopus/celt/mdct.c",
    "media/libopus/celt/modes.c",
    "media/libopus/celt/pitch.c",
    "media/libopus/celt/quant_bands.c",
    "media/libopus/celt/rate.c",
    "media/libopus/celt/vq.c",
    "media/libopus/celt/x86/celt_lpc_sse.c",
    "media/libopus/celt/x86/pitch_sse.c",
    "media/libopus/celt/x86/pitch_sse2.c",
    "media/libopus/celt/x86/pitch_sse4_1.c",
    "media/libopus/celt/x86/vq_sse2.c",
    "media/libopus/celt/x86/x86_celt_map.c",
    "media/libopus/celt/x86/x86cpu.c",
    "media/libopus/silk/A2NLSF.c",
    "media/libopus/silk/ana_filt_bank_1.c",
    "media/libopus/silk/arm/arm_silk_map.c",
    "media/libopus/silk/arm/biquad_alt_neon_intr.c",
    "media/libopus/silk/arm/LPC_inv_pred_gain_neon_intr.c",
    "media/libopus/silk/arm/NSQ_del_dec_neon_intr.c",
    "media/libopus/silk/arm/NSQ_neon.c",
    "media/libopus/silk/biquad_alt.c",
    "media/libopus/silk/bwexpander.c",
    "media/libopus/silk/bwexpander_32.c",
    "media/libopus/silk/check_control_input.c",
    "media/libopus/silk/CNG.c",
    "media/libopus/silk/code_signs.c",
    "media/libopus/silk/control_audio_bandwidth.c",
    "media/libopus/silk/control_codec.c",
    "media/libopus/silk/control_SNR.c",
    "media/libopus/silk/debug.c",
    "media/libopus/silk/dec_API.c",
    "media/libopus/silk/decode_core.c",
    "media/libopus/silk/decode_frame.c",
    "media/libopus/silk/decode_indices.c",
    "media/libopus/silk/decode_parameters.c",
    "media/libopus/silk/decode_pitch.c",
    "media/libopus/silk/decode_pulses.c",
    "media/libopus/silk/decoder_set_fs.c",
    "media/libopus/silk/enc_API.c",
    "media/libopus/silk/encode_indices.c",
    "media/libopus/silk/encode_pulses.c",
    "media/libopus/silk/fixed/apply_sine_window_FIX.c",
    "media/libopus/silk/fixed/arm/warped_autocorrelation_FIX_neon_intr.c",
    "media/libopus/silk/fixed/autocorr_FIX.c",
    "media/libopus/silk/fixed/burg_modified_FIX.c",
    "media/libopus/silk/fixed/corrMatrix_FIX.c",
    "media/libopus/silk/fixed/encode_frame_FIX.c",
    "media/libopus/silk/fixed/find_LPC_FIX.c",
    "media/libopus/silk/fixed/find_LTP_FIX.c",
    "media/libopus/silk/fixed/find_pitch_lags_FIX.c",
    "media/libopus/silk/fixed/find_pred_coefs_FIX.c",
    "media/libopus/silk/fixed/k2a_FIX.c",
    "media/libopus/silk/fixed/k2a_Q16_FIX.c",
    "media/libopus/silk/fixed/LTP_analysis_filter_FIX.c",
    "media/libopus/silk/fixed/LTP_scale_ctrl_FIX.c",
    "media/libopus/silk/fixed/noise_shape_analysis_FIX.c",
    "media/libopus/silk/fixed/pitch_analysis_core_FIX.c",
    "media/libopus/silk/fixed/process_gains_FIX.c",
    "media/libopus/silk/fixed/regularize_correlations_FIX.c",
    "media/libopus/silk/fixed/residual_energy16_FIX.c",
    "media/libopus/silk/fixed/residual_energy_FIX.c",
    "media/libopus/silk/fixed/schur64_FIX.c",
    "media/libopus/silk/fixed/schur_FIX.c",
    "media/libopus/silk/fixed/vector_ops_FIX.c",
    "media/libopus/silk/fixed/warped_autocorrelation_FIX.c",
    "media/libopus/silk/fixed/x86/burg_modified_FIX_sse.c",
    "media/libopus/silk/fixed/x86/vector_ops_FIX_sse.c",
    "media/libopus/silk/float/apply_sine_window_FLP.c",
    "media/libopus/silk/float/autocorrelation_FLP.c",
    "media/libopus/silk/float/burg_modified_FLP.c",
    "media/libopus/silk/float/bwexpander_FLP.c",
    "media/libopus/silk/float/corrMatrix_FLP.c",
    "media/libopus/silk/float/encode_frame_FLP.c",
    "media/libopus/silk/float/energy_FLP.c",
    "media/libopus/silk/float/find_LPC_FLP.c",
    "media/libopus/silk/float/find_LTP_FLP.c",
    "media/libopus/silk/float/find_pitch_lags_FLP.c",
    "media/libopus/silk/float/find_pred_coefs_FLP.c",
    "media/libopus/silk/float/inner_product_FLP.c",
    "media/libopus/silk/float/k2a_FLP.c",
    "media/libopus/silk/float/LPC_analysis_filter_FLP.c",
    "media/libopus/silk/float/LPC_inv_pred_gain_FLP.c",
    "media/libopus/silk/float/LTP_analysis_filter_FLP.c",
    "media/libopus/silk/float/LTP_scale_ctrl_FLP.c",
    "media/libopus/silk/float/noise_shape_analysis_FLP.c",
    "media/libopus/silk/float/pitch_analysis_core_FLP.c",
    "media/libopus/silk/float/process_gains_FLP.c",
    "media/libopus/silk/float/regularize_correlations_FLP.c",
    "media/libopus/silk/float/residual_energy_FLP.c",
    "media/libopus/silk/float/scale_copy_vector_FLP.c",
    "media/libopus/silk/float/scale_vector_FLP.c",
    "media/libopus/silk/float/schur_FLP.c",
    "media/libopus/silk/float/sort_FLP.c",
    "media/libopus/silk/float/warped_autocorrelation_FLP.c",
    "media/libopus/silk/float/wrappers_FLP.c",
    "media/libopus/silk/gain_quant.c",
    "media/libopus/silk/HP_variable_cutoff.c",
    "media/libopus/silk/init_decoder.c",
    "media/libopus/silk/init_encoder.c",
    "media/libopus/silk/inner_prod_aligned.c",
    "media/libopus/silk/interpolate.c",
    "media/libopus/silk/lin2log.c",
    "media/libopus/silk/log2lin.c",
    "media/libopus/silk/LP_variable_cutoff.c",
    "media/libopus/silk/LPC_analysis_filter.c",
    "media/libopus/silk/LPC_fit.c",
    "media/libopus/silk/LPC_inv_pred_gain.c",
    "media/libopus/silk/NLSF2A.c",
    "media/libopus/silk/NLSF_decode.c",
    "media/libopus/silk/NLSF_del_dec_quant.c",
    "media/libopus/silk/NLSF_encode.c",
    "media/libopus/silk/NLSF_stabilize.c",
    "media/libopus/silk/NLSF_unpack.c",
    "media/libopus/silk/NLSF_VQ.c",
    "media/libopus/silk/NLSF_VQ_weights_laroia.c",
    "media/libopus/silk/NSQ.c",
    "media/libopus/silk/NSQ_del_dec.c",
    "media/libopus/silk/pitch_est_tables.c",
    "media/libopus/silk/PLC.c",
    "media/libopus/silk/process_NLSFs.c",
    "media/libopus/silk/quant_LTP_gains.c",
    "media/libopus/silk/resampler.c",
    "media/libopus/silk/resampler_down2.c",
    "media/libopus/silk/resampler_down2_3.c",
    "media/libopus/silk/resampler_private_AR2.c",
    "media/libopus/silk/resampler_private_down_FIR.c",
    "media/libopus/silk/resampler_private_IIR_FIR.c",
    "media/libopus/silk/resampler_private_up2_HQ.c",
    "media/libopus/silk/resampler_rom.c",
    "media/libopus/silk/shell_coder.c",
    "media/libopus/silk/sigm_Q15.c",
    "media/libopus/silk/sort.c",
    "media/libopus/silk/stereo_decode_pred.c",
    "media/libopus/silk/stereo_encode_pred.c",
    "media/libopus/silk/stereo_find_predictor.c",
    "media/libopus/silk/stereo_LR_to_MS.c",
    "media/libopus/silk/stereo_MS_to_LR.c",
    "media/libopus/silk/stereo_quant_pred.c",
    "media/libopus/silk/sum_sqr_shift.c",
    "media/libopus/silk/table_LSF_cos.c",
    "media/libopus/silk/tables_gain.c",
    "media/libopus/silk/tables_LTP.c",
    "media/libopus/silk/tables_NLSF_CB_NB_MB.c",
    "media/libopus/silk/tables_NLSF_CB_WB.c",
    "media/libopus/silk/tables_other.c",
    "media/libopus/silk/tables_pitch_lag.c",
    "media/libopus/silk/tables_pulses_per_block.c",
    "media/libopus/silk/VAD.c",
    "media/libopus/silk/VQ_WMat_EC.c",
    "media/libopus/silk/x86/NSQ_del_dec_sse.c",
    "media/libopus/silk/x86/NSQ_sse.c",
    "media/libopus/silk/x86/VAD_sse.c",
    "media/libopus/silk/x86/VQ_WMat_EC_sse.c",
    "media/libopus/silk/x86/x86_silk_map.c",
    "media/libopus/src/analysis.c",
    "media/libopus/src/mlp.c",
    "media/libopus/src/mlp_data.c",
    "media/libopus/src/opus.c",
    "media/libopus/src/opus_decoder.c",
    "media/libopus/src/opus_encoder.c",
    "media/libopus/src/opus_multistream.c",
    "media/libopus/src/opus_multistream_decoder.c",
    "media/libopus/src/opus_multistream_encoder.c",
    "media/libopus/src/repacketizer.c",
    "media/libsoundtouch/src/AAFilter.cpp",
    "media/libsoundtouch/src/cpu_detect_x86.cpp",
    "media/libsoundtouch/src/FIFOSampleBuffer.cpp",
    "media/libsoundtouch/src/FIRFilter.cpp",
    "media/libsoundtouch/src/InterpolateCubic.cpp",
    "media/libsoundtouch/src/InterpolateLinear.cpp",
    "media/libsoundtouch/src/InterpolateShannon.cpp",
    "media/libsoundtouch/src/mmx_optimized.cpp",
    "media/libsoundtouch/src/RateTransposer.cpp",
    "media/libsoundtouch/src/SoundTouch.cpp",
    "media/libsoundtouch/src/SoundTouchFactory.cpp",
    "media/libsoundtouch/src/sse_optimized.cpp",
    "media/libsoundtouch/src/TDStretch.cpp",
    "media/libspeex_resampler/src/resample.c",
    "media/libspeex_resampler/src/resample_neon.c",
    "media/libspeex_resampler/src/resample_sse.c",
    "media/libspeex_resampler/src/simd_detect.cpp",
    "media/libvorbis/lib/vorbis_analysis.c",
    "media/libvorbis/lib/vorbis_bitrate.c",
    "media/libvorbis/lib/vorbis_block.c",
    "media/libvorbis/lib/vorbis_codebook.c",
    "media/libvorbis/lib/vorbis_envelope.c",
    "media/libvorbis/lib/vorbis_floor0.c",
    "media/libvorbis/lib/vorbis_floor1.c",
    "media/libvorbis/lib/vorbis_info.c",
    "media/libvorbis/lib/vorbis_lookup.c",
    "media/libvorbis/lib/vorbis_lpc.c",
    "media/libvorbis/lib/vorbis_lsp.c",
    "media/libvorbis/lib/vorbis_mapping0.c",
    "media/libvorbis/lib/vorbis_mdct.c",
    "media/libvorbis/lib/vorbis_psy.c",
    "media/libvorbis/lib/vorbis_registry.c",
    "media/libvorbis/lib/vorbis_res0.c",
    "media/libvorbis/lib/vorbis_sharedbook.c",
    "media/libvorbis/lib/vorbis_smallft.c",
    "media/libvorbis/lib/vorbis_synthesis.c",
    "media/libvorbis/lib/vorbis_window.c",
    "media/libvorbis/lib/vorbisenc.c",
    "memory/fallible/fallible.cpp",
    "memory/mozalloc/mozalloc.cpp",
    "memory/mozalloc/mozalloc_abort.cpp",
    "memory/mozalloc/mozalloc_oom.cpp",
    "mfbt/Assertions.cpp",
    "mfbt/ChaosMode.cpp",
    "mfbt/HashFunctions.cpp",
    "mfbt/Unused.cpp",
    "mozglue/misc/ConditionVariable_posix.cpp",
    "mozglue/misc/Mutex_posix.cpp",
    "mozglue/misc/Printf.h",
    "mozglue/misc/Printf.cpp",
    "mozglue/misc/TimeStamp_darwin.cpp",
    "mozglue/misc/TimeStamp_posix.cpp",
    "mozglue/misc/TimeStamp_windows.cpp",
    "mozglue/misc/TimeStamp.cpp",
    "nsprpub/pr/src/io/priometh.c",
    "nsprpub/pr/src/io/prfdcach.c",
    "nsprpub/pr/src/io/prlayer.c",
    "nsprpub/pr/src/io/prlog.c",
    "nsprpub/pr/src/io/prmapopt.c",
    "nsprpub/pr/src/io/prmmap.c",
    "nsprpub/pr/src/io/prmwait.c",
    "nsprpub/pr/src/io/prprf.c",
    "nsprpub/pr/src/linking/prlink.c",
    "nsprpub/pr/src/malloc/prmem.c",
    "nsprpub/pr/src/md/prosdep.c",
    "nsprpub/pr/src/md/unix/darwin.c",
    "nsprpub/pr/src/md/unix/linux.c",
    "nsprpub/pr/src/md/unix/unix.c",
    "nsprpub/pr/src/md/unix/unix_errors.c",
    "nsprpub/pr/src/memory/prseg.c",
    "nsprpub/pr/src/misc/pratom.c",
    "nsprpub/pr/src/misc/prdtoa.c",
    "nsprpub/pr/src/misc/prenv.c",
    "nsprpub/pr/src/misc/prerr.c",
    "nsprpub/pr/src/misc/prerror.c",
    "nsprpub/pr/src/misc/prerrortable.c",
    "nsprpub/pr/src/misc/prinit.c",
    "nsprpub/pr/src/misc/prinrval.c",
    "nsprpub/pr/src/misc/prtime.c",
    "nsprpub/pr/src/misc/prnetdb.c",
    "nsprpub/pr/src/pthreads/ptio.c",
    "nsprpub/pr/src/pthreads/ptmisc.c",
    "nsprpub/pr/src/pthreads/ptsynch.c",
    "nsprpub/pr/src/pthreads/ptthread.c",
    "nsprpub/pr/src/threads/prcmon.c",
    "nsprpub/pr/src/threads/prrwlock.c",
    "nsprpub/pr/src/threads/prtpd.c",
    "tools/profiler/core/platform.cpp",
    "toolkit/crashreporter/nsExceptionHandler.cpp",
    "toolkit/crashreporter/ThreadAnnotation.cpp",
    "toolkit/library/StaticXULComponentsStart.cpp",
    "toolkit/library/StaticXULComponentsEnd/StaticXULComponentsEnd.cpp",
    "xpcom/base/ClearOnShutdown.cpp",
    "xpcom/base/nsCOMPtr.cpp",
    "xpcom/base/nsClassInfoImpl.cpp",
    "xpcom/base/nsID.cpp",
    "xpcom/base/nsISupportsImpl.cpp",
    "xpcom/base/nsMemory.cpp",
    "xpcom/base/nsWeakReference.cpp",
    "xpcom/components/GenericFactory.cpp",
    "xpcom/ds/PLDHashTable.cpp",
    "xpcom/ds/nsCOMArray.cpp",
    "xpcom/ds/nsEnumeratorUtils.cpp",
    "xpcom/ds/nsQuickSort.cpp",
    "xpcom/ds/nsSupportsPrimitives.cpp",
    "xpcom/ds/nsTArray.cpp",
    "xpcom/ds/nsTObserverArray.cpp",
    "xpcom/io/nsDirectoryService.cpp",
    "xpcom/string/nsASCIIMask.cpp",
    "xpcom/string/nsDependentString.cpp",
    "xpcom/string/nsDependentSubstring.cpp",
    "xpcom/string/nsPromiseFlatString.cpp",
    "xpcom/string/nsReadableUtils.cpp",
    "xpcom/string/nsReadableUtilsSSE2.cpp",
    "xpcom/string/nsString.cpp",
    "xpcom/string/nsStringComparator.cpp",
    "xpcom/string/nsStringObsolete.cpp",
    "xpcom/string/nsSubstring.cpp",
    "xpcom/string/nsSubstringTuple.cpp",
    "xpcom/string/nsTDependentString.cpp",
    "xpcom/string/nsTDependentSubstring.cpp",
    "xpcom/string/nsTextFormatter.cpp",
    "xpcom/string/nsTPromiseFlatString.cpp",
    "xpcom/string/nsTString.cpp",
    "xpcom/string/nsTStringComparator.cpp",
    "xpcom/string/nsTStringObsolete.cpp",
    "xpcom/string/nsTSubstring.cpp",
    "xpcom/string/nsTSubstringTuple.cpp",
    "xpcom/string/nsUTF8UtilsSSE2.cpp",
    "xpcom/string/precompiled_templates.cpp",
    "xpcom/threads/EventQueue.cpp",
    "xpcom/threads/nsILabelableRunnable.cpp",
    "xpcom/threads/nsThreadManager.cpp",
    "xpcom/threads/nsThreadPool.cpp",
    "xpcom/threads/nsThreadUtils.cpp",
    "xpcom/threads/nsTimerImpl.cpp",
    "xpcom/threads/PrioritizedEventQueue.cpp",
    "xpcom/threads/RecursiveMutex.cpp",
    "xpcom/threads/SharedThreadPool.cpp",
    "xpcom/threads/SynchronizedEventQueue.cpp",
    "xpcom/threads/SystemGroup.cpp",
    "xpcom/threads/TaskQueue.cpp",
    "xpcom/threads/ThreadEventQueue.cpp",
    "xpcom/threads/ThreadEventTarget.cpp",
    "xpcom/threads/TimerThread.cpp",
]

objdir_files = [
    "cubeb/cubeb.h",
    "cubeb/cubeb_export.h",
    "ErrorList.h",
    "js-config.h",
    "mozilla/TelemetryHistogramEnums.h",
    "mozilla/TelemetryScalarEnums.h",
    "nsIArray.h",
    "nsIArrayExtensions.h",
    "nsIAtom.h",
    "nsIAudioDeviceInfo.h",
    "nsICategoryManager.h",
    "nsIClassInfo.h",
    "nsIComponentManager.h",
    "nsIComponentRegistrar.h",
    "nsIConsoleMessage.h",
    "nsIConsoleService.h",
    "nsIContentPolicy.h",
    "nsID.h",
    "nsIDirectoryService.h",
    "nsIErrorService.h",
    "nsIEventTarget.h",
    "nsIFactory.h",
    "nsIFile.h",
    "nsIHashable.h",
    "nsIID.h",
    "nsIIdlePeriod.h",
    "nsIIdleRunnable.h",
    "nsIInputStream.h",
    "nsIInterfaceInfoManager.h",
    "nsIInterfaceRequestor.h",
    "nsILoadGroup.h",
    "nsIMemory.h",
    "nsIMutableArray.h",
    "nsINamed.h",
    "nsINetUtil.h",
    "nsIObserver.h",
    "nsIObserverService.h",
    "nsIPersistentProperties2.h",
    "nsIPrefBranch.h",
    "nsIPrefService.h",
    "nsIProperties.h",
    "nsIRequest.h",
    "nsIRunnable.h",
    "nsISerialEventTarget.h",
    "nsIServiceManager.h",
    "nsISimpleEnumerator.h",
    "nsIStringBundle.h",
    "nsIStringBundleOverride.h",
    "nsIStringEnumerator.h",
    "nsISupports.h",
    "nsISupportsBase.h",
    "nsISupportsPrimitives.h",
    "nsISupportsPriority.h",
    "nsISupportsUtils.h",
    "nsIThread.h",
    "nsIThreadInternal.h",
    "nsIThreadManager.h",
    "nsIThreadPool.h",
    "nsITimer.h",
    "nsIWeakReference.h",
    "nspr/plhash.h",
    "nspr/prcpucfg.h",
    "nspr/prenv.h",
    "nspr/prinet.h",
    "nspr/prinit.h",
    "nspr/prinrval.h",
    "nspr/prio.h",
    "nspr/prprf.h",
    "nspr/prthread.h",
    "nspr/prwin16.h",
    "nsrootidl.h",
    "nsStaticAtom.h",
    "soundtouch/FIFOSamplePipe.h",
    "soundtouch/SoundTouch.h",
    "soundtouch/soundtouch_config.h",
    "soundtouch/STTypes.h",
    "speex/speex_resampler.h",
]

def get_obj_dir_path(src_dir):
    if sys.platform == 'darwin':
        obj_dir = "obj-x86_64-apple-darwin16.7.0"
    elif sys.platform == 'linux':
        obj_dir = "obj-x86_64-pc-linux-gnu"
    else:
        raise Exception("Unsupported platform: {}".format(sys.platform))
    return os.path.join(src_dir, obj_dir)

def get_obj_dir_include_path(src_dir):
    return os.path.join(get_obj_dir_path(src_dir), "dist", "include/")

def get_obj_dir_config_path(src_dir):
    return os.path.join(get_obj_dir_path(src_dir), "config/")

def verify_files_present(src_dir, dst_dir):
    had_error = False
    for (src, dst) in header_files:
        p = Path(src_dir + src)
        if not p.is_file():
            print("ERROR: Header file '{}' is not a valid file.".format(src))
            had_error = True;
    for src in src_files:
        if not Path(src_dir + src).is_file():
            print("ERROR: Source file '{}' is not a valid file.".format(src))
            had_error = True;
    obj_include_dir = get_obj_dir_include_path(src_dir)
    for src in objdir_files:
        if not(Path(obj_include_dir + src).is_file()):
            print("ERROR: Object dir file '{}' is not a valid file.".format(src))
            had_error = True;
    return not int(had_error)

def ensure_dir_exists(dst_path):
    dirname = os.path.dirname(dst_path)
    if not os.path.exists(dirname):
        os.makedirs(dirname)

def copy_files(src_dir, dst_dir):
    for (src, dst) in header_files:
        ensure_dir_exists(dst_dir + "include/" + dst)
        copyfile(src_dir + src, dst_dir + "include/" + dst)
    for src in src_files:
        ensure_dir_exists(dst_dir + "src/" + src)
        copyfile(src_dir + src, dst_dir + "src/" + src)
    obj_include_dir = get_obj_dir_include_path(src_dir)
    for src in objdir_files:
        ensure_dir_exists(dst_dir + "include/" + src)
        copyfile(obj_include_dir + src, dst_dir + "include/" + src)

def remove_previous_copy(src_dir, dst_dir):
    rmtree(dst_dir + "include/")
    rmtree(dst_dir + "src/")

def write_gecko_revision_file(src_dir):
    result = subprocess.run(['hg', 'log', src_dir, '--limit', '1'], stdout=subprocess.PIPE)
    first_line = result.stdout.splitlines()[0]
    revision = re.match(b'changeset:\s+(.*)', first_line).group(1)
    with open('GECKO_REVISION', 'w') as f:
        f.write(revision.decode('utf-8') + '\n')
        f.close()

def write_unified_cpp_file(dir):
    cpps = sorted([f for f in listdir(dir)
      if f.endswith(".cpp") and not os.path.basename(f).startswith("nsT") and not "SSE" in f])
    with open(dir + os.path.sep + "unified.cpp", "w") as f:
      for cpp_file in cpps:
        f.write("#include \"{}\"\n".format(cpp_file))

def extract_pref_from_line(line):
    m = re.match(r'pref\((".*?"),\s*(.*)\);', line)
    if not m:
        print("extract_pref_from_line() failed on {}".format(line))
        sys.exit(1)
    name = m.group(1)
    val = m.group(2)
    kind = ""
    if val == "true" or val == "false":
        kind = "bool"
    elif val.startswith('"') and val.endswith('"'):
        kind = "string"
    else:
        kind = "int"
    return (name, val, kind)

def is_preprocessor_line(line):
    return (line.startswith("#if") or
            line.startswith("#endif") or
            line.startswith("#else"))

def extract_preferences(lines):
    # Returns a triple of lists of ((pref,value),[include-guard]).
    #   ([((bool_pref, value), [guards])],
    #    [((int_pref, value), [guards])],
    #    [((string_pref, value), [guards])])
    i = 0
    guards = []
    bool_prefs = []
    int_prefs = []
    string_prefs = []
    prefs = dict({"bool": [], "int": [], "string": []});
    while i < len(lines):
        line = lines[i]
        if line.startswith("#if"):
            guards.append(line)
        elif line.startswith("pref"):
            (pref, value, kind) = extract_pref_from_line(line)
            prefs[kind] += [((pref, value), guards[:])]
        elif line.startswith("#else"):
            guards.append(line)
        elif line.startswith("#endif"):
            if guards[-1].startswith("#else"):
                guards.pop()
            guards.pop()
        i += 1
    # Sort the lists based on pref name, so we can binary search it in
    # the Preferences implementation.
    bool_prefs = list(sorted(prefs["bool"], key=lambda x: x[0][0]))
    int_prefs = list(sorted(prefs["int"], key=lambda x: x[0][0]))
    string_prefs = list(sorted(prefs["string"], key=lambda x: x[0][0]))
    return (bool_prefs, int_prefs, string_prefs)

def write_pref_group(dst, prefs, prefix, pref_type):
    dst.write("static const " + pref_type + " s" + prefix + "" + pref_type + "s[] = {\n")
    for ((name, value),guards) in prefs:
        for guard in guards:
            dst.write(guard)
        dst.write("  { " + name + ", " + value + " },\n")
        for guard in guards:
            if not guard.startswith("#else"):
                dst.write("#endif // " + guard)
    dst.write("};\n\n")

def copy_media_prefs(src_pref_file, dst_pref_file, prefix):
    is_media_pref = re.compile(r'pref\("media.')
    with open(src_pref_file, "r") as src:
        # Filter out non media pref and non preprocessor lines.
        lines = []
        for line in src:
            if is_media_pref.match(line) or is_preprocessor_line(line):
                lines += [line]

        (bool_prefs, int_prefs, string_prefs) = extract_preferences(lines)
        with open(dst_pref_file, "w") as dst:
            write_pref_group(dst, bool_prefs, prefix, "BoolPref")
            write_pref_group(dst, int_prefs, prefix, "IntPref")
            write_pref_group(dst, string_prefs, prefix, "StringPref")

def main(args):
    if len(args) != 2:
        print("Usage: python3 import.py <src_dir> <dst_dir>")
        return 1

    src_dir = os.path.abspath(args[0]) + os.path.sep
    dst_dir = os.path.abspath(args[1]) + os.path.sep

    if not verify_files_present(src_dir, dst_dir):
        return 1

    # Create copies of Gecko's media prefs.
    copy_media_prefs(src_dir + "modules/libpref/init/all.js", dst_dir + "glue/prefs_common.cpp", "Common")
    copy_media_prefs(src_dir + "browser/app/profile/firefox.js", dst_dir + "glue/prefs_desktop.cpp", "Desktop")
    copy_media_prefs(src_dir + "mobile/android/app/mobile.js", dst_dir + "glue/prefs_android.cpp", "Android")

    remove_previous_copy(src_dir, dst_dir)
    copy_files(src_dir, dst_dir)
    # Gecko's string classes only build in unified mode...
    write_unified_cpp_file(dst_dir + "src/xpcom/string")
    write_gecko_revision_file(src_dir)
    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
